### ISSUE TITLE
Crash in RHH initialisation

### ISSUE THREAD

**Issue by jmmcd** [jmmcd/PonyGE2#26]
(I've just pushed some code for a sequence-match problem, please pull it to see the problem below.)

The following runs ok: 

`python ponyge.py --bnf_grammar sequence_match.pybnf --fitness_function sequence_match --target "[0, 5, 0, 5, 0, 5]" --extra_fitness_parameters "alpha=0.5, beta=0.5, gamma=0.5" --generations 10 --population 10 --initialisation operators.initialisation.random_init` 

But the following crashes: 

`python ponyge.py --bnf_grammar sequence_match.pybnf --fitness_function sequence_match --target "[0, 5, 0, 5, 0, 5]" --extra_fitness_parameters "alpha=0.5, beta=0.5, gamma=0.5" --generations 10 --population 10`

The difference is just in the init operator (`random_init` versus `rhh`).

```python
Traceback (most recent call last):
  File "ponyge.py", line 33, in <module>
    mane()
  File "ponyge.py", line 22, in mane
    individuals = params['SEARCH_LOOP']()
  File "/Users/jmmcd/Documents/vc/PonyGE2/src/algorithm/search_loop.py", line 16, in search_loop
    individuals = params['INITIALISATION'](params['POPULATION_SIZE'])
  File "/Users/jmmcd/Documents/vc/PonyGE2/src/operators/initialisation.py", line 79, in rhh
    ind = generate_ind_tree(depth, "full")
  File "/Users/jmmcd/Documents/vc/PonyGE2/src/operators/initialisation.py", line 123, in generate_ind_tree
    0, 0, 0, max_depth - 1)
  File "/Users/jmmcd/Documents/vc/PonyGE2/src/representation/tree.py", line 296, in generate_tree
    nodes, depth, max_depth, depth_limit - 1)
  File "/Users/jmmcd/Documents/vc/PonyGE2/src/representation/tree.py", line 264, in generate_tree
    chosen_prod = choice(available)
  File "/Users/jmmcd/anaconda3/lib/python3.5/random.py", line 255, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence```

**Comment by mikefenton** [comment]
Looking in to this now, it's a minor bug with the implementation of "full" initialisation.

**Comment by mikefenton** [comment]
Fixed.
